default:
  image: fedora:44
  before_script:
    - dnf install -y unzip npm
    - npm config set @glassway:registry "https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"
    - npm config set -- "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
    - curl -fsSL https://deno.land/install.sh | sh
    - export PATH="$PATH:$HOME/.deno/bin"

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - deno install

# TODO: eventually deno lint here?
unit-test-job:
  stage: test
  script:
    - deno test -A

lint-test-job:
  stage: test
  script:
    - deno task check

# TODO: deno bump-version patch
deploy-job:
  stage: deploy
  when: manual
  script:
    - cd packages
    - cd architect && deno pack --output result.tgz
    - npm publish ./result.tgz
    - cd ./../
    - cd architect-k8s && deno pack --output result.tgz
    - npm publish ./result.tgz
    - cd ./../
    - cd architect-wrapper && deno pack --output result.tgz
    - npm publish ./result.tgz
