apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/component: architect-controller
    app.kubernetes.io/instance: architect-system
    app.kubernetes.io/part-of: architect
  name: targets.architect.glassway.net
spec:
  group: architect.glassway.net
  names:
    kind: Target
    listKind: TargetList
    plural: targets
    shortNames:
      - tgt
    singular: target
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Target is the Schema for the targets API
          properties:
            apiVersion:
              description: >-
                APIVersion defines the versioned schema of this representation
                of an object.

                Servers should convert recognized schemas to the latest internal
                value, and

                may reject unrecognized values.

                More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: >-
                Kind is a string value representing the REST resource this
                object represents.

                Servers may infer this from the endpoint the client submits
                requests to.

                Cannot be updated.

                In CamelCase.

                More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: TargetSpec defines the desired state of Target
              properties:
                plugins:
                  minProperties: 1
                  properties:
                    kubernetes:
                      description: Configuration for the Kubernetes plugin
                      properties:
                        client:
                          properties:
                            context:
                              type: string
                          required:
                            - context
                        dns:
                          type: string
                        ns:
                          description: Configuration for default cluster namespaces
                          properties:
                            features:
                              type: string
                            operators:
                              type: string
                            services:
                              type: string
                        podNetwork:
                          properties:
                            ipFamilies:
                              items:
                                type: string
                                enum: [ "IPv4", "IPv6" ]
                              type: array
                          required:
                            - ipFamilies
                          type: object
                        flavor:
                          type: string
                          enum: [ "docker-desktop", "kind", "k3s", "talos" ]
                        version:
                          type: string
                        metal:
                          type: object
                          properties:
                            nodes:
                              type: integer
                          required: [ "nodes" ]
                      required:
                        - client
                        - dns
                        - podNetwork
                        - flavor
                        - version
                        - metal
                capabilities:
                  description: >-
                    Capabilities is a list of capability identifiers that this target exposes but are not created by components within the build tree.
                  items:
                    type: object
                    properties:
                      class:
                        type: string
                      options:
                        type: object
                    required: [ "class" ]
                  type: array
                components:
                  description: >-
                    Components is a list of components that must be deployed in
                    the target
                  items:
                    properties:
                      class:
                        type: string
                      name:
                        type: string
                      options:
                        type: object
                      context:
                        type: object
                    required: [ "class" ]
                    type: object
                  type: array
          required:
            - apiVersion
            - kind
            - metadata
            - spec
      served: true
      storage: false
